# Generated by Django 5.2.3 on 2025-07-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        ("users", "0011_daycarecenter_featured_services_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaycarePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("hourly", "Hourly"),
                            ("drop_in", "Drop In"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_unit", models.CharField(default="month", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daycare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="users.daycarecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["booking_type"],
                "unique_together": {("daycare", "booking_type")},
            },
        ),
    ]
