# Generated by Django 5.2.3 on 2025-07-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_daycarepricing'),
        ('users', '0011_daycarecenter_featured_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='emergency_contact_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.emergencycontact'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay'), ('sure_cash', 'SureCash')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('monthly', 'Monthly Care'), ('daily', 'Daily Care')], max_length=20),
        ),
        migrations.AlterField(
            model_name='daycarepricing',
            name='booking_type',
            field=models.CharField(choices=[('monthly', 'Monthly Care'), ('daily', 'Daily Care')], max_length=20),
        ),
    ]
