# Generated by Django 5.2.3 on 2025-07-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_emergency_contact_name_and_more'),
        ('users', '0011_daycarecenter_featured_services_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daycarepricing',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='daycarepricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='daycarepricing',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily')], default='Monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='daycarepricing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.emergencycontact'),
        ),
        migrations.RemoveField(
            model_name='daycarepricing',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='daycarepricing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='daycarepricing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='daycarepricing',
            name='duration_unit',
        ),
        migrations.RemoveField(
            model_name='daycarepricing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='daycarepricing',
            name='updated_at',
        ),
    ]
