# Generated by Django 5.1.5 on 2025-06-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaycareCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("area", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("rating", models.FloatField(default=0.0)),
                ("services", models.TextField()),
                ("images", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("daycare_id", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("daycare", "Daycare"),
                    ("super_admin", "Super Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
