# Generated by Django 5.2.3 on 2025-07-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_email_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daycarecenter',
            old_name='license',
            new_name='nid_number',
        ),
    ]
