# Generated by Django 5.1.5 on 2025-06-21 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="daycarecenter",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daycare_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
