# Generated by Django 5.2.3 on 2025-07-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_license_daycarecenter_nid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarecenter',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
