# Generated by Django 5.1.5 on 2025-06-21 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_daycarecenter_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daycarecenter",
            name="daycare_id",
        ),
        migrations.RemoveField(
            model_name="daycarecenter",
            name="email",
        ),
        migrations.RemoveField(
            model_name="daycarecenter",
            name="password",
        ),
        migrations.AlterField(
            model_name="daycarecenter",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daycare_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
