# Generated by Django 5.2.3 on 2025-06-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_daycarecenter_daycare_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarecenter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='daycare_docs/'),
        ),
        migrations.AddField(
            model_name='daycarecenter',
            name='license',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
