# Generated by Django 5.1.5 on 2025-07-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_daycarecenter_images_daycareimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daycareimage",
            name="image",
            field=models.ImageField(upload_to="media/daycare_docs/"),
        ),
    ]
