# Generated by Django 5.1.5 on 2025-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_daycareimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daycarecenter",
            name="image",
            field=models.ImageField(
                blank=True,
                default="daycare_docs/default.jpg",
                upload_to="daycare_docs/",
            ),
        ),
        migrations.AlterField(
            model_name="daycareimage",
            name="image",
            field=models.ImageField(upload_to="daycare_images/"),
        ),
    ]
