# Generated by Django 5.1.5 on 2025-07-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_daycarecenter_image_alter_daycareimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="address",
        ),
        migrations.RemoveField(
            model_name="parent",
            name="emergency_contact",
        ),
        migrations.AddField(
            model_name="parent",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="parent_images/"),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state_division", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Bangladesh", max_length=100)),
                (
                    "parent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="users.parent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(
                        blank=True,
                        help_text="Any special needs, allergies, or medical conditions",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="child_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.parent",
                    ),
                ),
            ],
            options={
                "ordering": ["date_of_birth"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("grandparent", "Grandparent"),
                            ("friend", "Friend"),
                            ("neighbor", "Neighbor"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_primary", models.CharField(max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="emergency_contact_photos/"
                    ),
                ),
                (
                    "is_authorized_pickup",
                    models.BooleanField(
                        default=False, help_text="Can this person pick up your child?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this contact"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="users.parent",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
    ]
