# Generated by Django 5.2.3 on 2025-07-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_parent_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emergencycontact",
            options={},
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="parent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_contact",
                to="users.parent",
            ),
        ),
    ]
