# Generated by Django 5.2.3 on 2025-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_emergencycontact_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="state_division",
        ),
        migrations.AddField(
            model_name="address",
            name="area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gulshan", "Gulshan"),
                    ("banani", "Banani"),
                    ("uttara", "Uttara"),
                    ("mirpur", "Mirpur"),
                    ("wari", "Wari"),
                    ("dhanmondi", "Dhanmondi"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="daycarecenter",
            name="area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gulshan", "Gulshan"),
                    ("banani", "Banani"),
                    ("uttara", "Uttara"),
                    ("mirpur", "Mirpur"),
                    ("wari", "Wari"),
                    ("dhanmondi", "Dhanmondi"),
                ],
                max_length=20,
            ),
        ),
    ]
