# Generated by Django 5.2.3 on 2025-07-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_address_state_division_address_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="daycarecenter",
            name="featured_services",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="daycarecenter",
            name="pricing",
            field=models.TextField(blank=True),
        ),
    ]
