# Generated by Django 5.2.3 on 2025-07-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_daycarecenter_featured_services_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daycarecenter",
            name="pricing",
        ),
    ]
