# Generated by Django 5.2.3 on 2025-06-19 00:28

import parent_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parent",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", parent_auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
