# Generated by Django 5.2.3 on 2025-06-19 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent_auth", "0002_alter_parent_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="joined_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="joined_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="parent",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="parent",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
