name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: pip install -r core/requirements.txt
      
      - name: Create .env file
        working-directory: core
        run: |
          touch .env
          echo "SECRET_KEY= ${{ secrets.SECRET_KEY }}" >> .env
          echo "EMAIL_HOST=${{'smtp.gmail.com'}}" >> .env 
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "EMAIL_USE_TLS=${{ 'True' }}" >> .env
          echo "EMAIL_USE_SSL=${{  'False' }}" >> .env
          echo "DEFAULT_FROM_EMAIL=${{ 'Daycare Connect <noreply@daycareconnect.com>' }}" >> .env
          
      - name: Debug Python environment
        run: |
          python -V
          pip list
          ls -la
          echo "DEBUG: DATABASE_URL=$DATABASE_URL"
          
      - name: Run DB migrations
        run: python manage.py migrate --noinput --verbosity 3
      - name: Run tests and generate coverage report
        working-directory: core
        run: |
          python manage.py makemigrations
          python manage.py migrate
          coverage erase
          coverage run manage.py test
          coverage xml -o coverage.xml
        env:
          DJANGO_SETTINGS_MODULE: core.settings

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          args: >
            -Dsonar.organization=mhtasnia
            -Dsonar.projectKey=mhtasnia_Daycare-Connect
            -Dsonar.projectBaseDir=core
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.12
